wandb_version: 1

lr:
  desc: null
  value: 0.0024433168493508744
output_path:
  desc: null
  value: /home/mila/a/aliakbar.ghayouri-sales/scratch/movasaghi_files/xray_classify/output
weight_decay:
  desc: null
  value: 0.0024432745571222455
_wandb:
  desc: null
  value:
    python_version: 3.8.2
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1682748633.525195
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      - 37
      4: 3.8.2
      5: 0.15.0
      8:
      - 2
      - 5
