wandb_version: 1

lr:
  value: 0.0005319329067425563
output_path:
  value: /home/mila/a/aliakbar.ghayouri-sales/scratch/movasaghi_files/xray_classify/output
weight_decay:
  value: 2.3638272059921014e-08
