wandb_version: 1

lr:
  value: 0.013139082641887793
output_path:
  value: /home/mila/a/aliakbar.ghayouri-sales/scratch/movasaghi_files/xray_classify/output
weight_decay:
  value: 1.5561566603213443e-08
