wandb_version: 1

lr:
  value: 0.0024433168493508744
output_path:
  value: /home/mila/a/aliakbar.ghayouri-sales/scratch/movasaghi_files/xray_classify/output
weight_decay:
  value: 0.0024432745571222455
