wandb_version: 1

lr:
  value: 0.023901189011966303
output_path:
  value: /home/mila/a/aliakbar.ghayouri-sales/scratch/movasaghi_files/xray_classify/output
weight_decay:
  value: 1.5441546815965658e-07
