wandb_version: 1

lr:
  value: 0.00023628075738312023
output_path:
  value: /home/mila/a/aliakbar.ghayouri-sales/scratch/movasaghi_files/xray_classify/output
weight_decay:
  value: 3.959601415771039e-08
