wandb_version: 1

lr:
  value: 0.0005308937693601919
output_path:
  value: /home/mila/a/aliakbar.ghayouri-sales/scratch/movasaghi_files/xray_classify/output
weight_decay:
  value: 2.8549665234990028e-08
